### PR TITLE
Update flurry

### PR DESCRIPTION
**Pull request by ibraheemdev**

### CODE REVIEW

**Comment by xacrimon** [comment]
Hm, this is really cool but the one thing is the repin frequency. I'm not sure micromanaging guards like this is realistic in a real-world scenario when you're likely accessing the map from say a web server middleware invocation. I try to avoid any unrealistic benchmark-number-go-vroom oriented scenarios. What do you think?

**Comment by ibraheemdev** [comment]
I don't think it's really unrealistic to have thread-local handles that you refresh every once in a while, but I removed it.

**Comment by ibraheemdev** [comment]
Friendly reminder @xacrimon :)

**Comment by loyd** [comment]
I think now `0.5` in https://github.com/xacrimon/conc-map-bench/blob/master/scripts/bench.bash#L34 can be removed

**Pull request merged**
